### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [minwang2022/SplitDice#2]
- [x] What is the `share` column on the generate expense table? 
- [x] Expenses have a lot of information on them (like belonging to a category, the ability to add notes, etc.), please create tables to account for that 
- [x] Users are able to comment on expenses - please add a table to account for this 
- [x] Please create a table for Groups (likely a groups table with a title for the group and an ID and a joins table that connects groups and users since users can belong to multiple groups and groups have multiple users) 

Let me know if you have any questions!

**Comment by minwang2022** [comment]
1. Share column has been changed to expense_split_percentage with data type of float. 
 2. Expense table added column of belong_to_group_id, category, note.
 3. Added comment table taking care of comment under each expense.
 4. Added group table to associate with all the group members.
